#!/usr/bin/env bash

set -e

base_url='http://geo.devtrac.org/api'

echo "# Authenticating..."
auth_data="username=${1:?Username not found}&password=${2:?Password not found}"
login_result=`curl -v -d "$auth_data" "$base_url/user/login.json"`

session_id=`echo $login_result | cut -d '"' -f4`
session_name=`echo $login_result | cut -d '"' -f8`
user_id=`echo $login_result | cut -d '"' -f14`

echo "user_id = $user_id"
echo "session_name = $session_name"
echo "session_id = $session_id"

cookie="$session_name=$session_id"

image_name="site_image.png"
image_path="./script/${image_name}"
image_data_file="${image_path}.data"

openssl enc -base64 -in $image_path | tr -d '\n' > "$image_data_file"

image_size=`cat ${image_data_file} | wc -c | tr -d ' \n'`

post_data="uid=$user_id&filesize=$image_size&filename=$image_name"

echo

echo "# Uploading image..."
upload_file_result=`curl --trace-ascii 'curl.log' -b "$cookie" -d "$post_data" --data-urlencode "file@${image_data_file}" "$base_url/file"`
fid=`echo $upload_file_result | cut -d ' ' -f3`
echo "fid = $fid"

rm -f "$image_data_file"

